name: gamenight
description: GameNight player app. Join a GameNight on your local network, draw your face and manage tonight's playlist.
publish_to: none
version: 0.1.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  mobile_scanner: ^7.0.1
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.3
  video_player: ^2.14.1
  web: ^1.1.1
  webview_flutter: ^4.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  url_launcher_platform_interface: ^2.3.2
  plugin_platform_interface: ^2.1.8

flutter:
  uses-material-design: true
