// Generated by tools/layout_lobby.py; keep map and door anchors together.
pub(super) const DOOR_X: [f32; 8] = [160., 256., 352., 448., 544., 640., 736., 832.];
pub(super) const DOOR_Y: f32 = 146.;
pub(super) const PLAYER_Y: f32 = 120.;
