// Generated by tools/layout_lobby.py; keep map and door anchors together.
pub(super) const DOOR_X: [f32; 8] = [160., 272., 384., 496., 608., 720., 832., 944.];
pub(super) const DOOR_Y: f32 = 146.;
pub(super) const PLAYER_Y: f32 = 120.;
