#!/usr/bin/env python3
"""Write assets/demo-faces.json: real GameNight faces for the offline demo.

Four faces come from the character editor recipes (web/host.html, generated by
scripts/generate-host-faces.cjs). The rest are the host's own guest faces: a
daemon is started, guests join without art, and the faces it assigns are kept.

    cargo build -p gamenight-daemon && python lobbies/game-room/tools/demo_faces.py
"""
import json, os, re, socket, subprocess, tempfile, time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
OUT = Path(__file__).resolve().parents[1] / "assets" / "demo-faces.json"


def editor_faces():
    html = (ROOT / "web/host.html").read_text()
    data = json.loads(re.search(r'<template id="host-character-data">(.*?)</template>', html, re.S).group(1))
    faces = []
    for name, runs in data.items():
        px = [None] * (48 * 48)
        for x, y, w, color in runs:
            for i in range(w): px[y * 48 + x + i] = color
        faces.append({"source": "editor:" + name, "avatar": json.dumps({"v": 1, "w": 48, "h": 48, "px": px})})
    return faces


def guest_faces(count):
    with socket.socket() as probe:
        probe.bind(("127.0.0.1", 0)); port = probe.getsockname()[1]
    with tempfile.TemporaryDirectory() as temp:
        env = {k: v for k, v in os.environ.items() if not k.startswith("GAMENIGHT")}
        env.update(GAMENIGHT_ADDR=f"127.0.0.1:{port}", GAMENIGHT_NO_LOBBY_WATCH="1", GAMENIGHT_NO_MUSIC="1",
                   GAMENIGHT_TEST_NO_CONTROLLERS="1", HOME=temp)
        daemon = subprocess.Popen([str(ROOT / "target/debug/gamenight-daemon")], env=env, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        try:
            for _ in range(100):
                try: sock = socket.create_connection(("127.0.0.1", port), timeout=5); break
                except OSError: time.sleep(0.05)
            f = sock.makefile("rwb")
            send = lambda m: (f.write((json.dumps(m) + "\n").encode()), f.flush())
            send({"type": "hello", "role": "overlay"})
            party = json.loads(f.readline())["party"]
            for i in range(count): send({"type": "join_party", "name": f"Guest {i}"})
            while len(party["players"]) < count or not all(p.get("avatar") for p in party["players"]):
                message = json.loads(f.readline())
                if message["type"] == "party_state": party = message["party"]
            return [{"source": "guest", "avatar": p["avatar"], "color": p.get("color"), "skin_color": p.get("skin_color")} for p in party["players"]]
        finally:
            daemon.terminate(); daemon.wait()


faces = editor_faces() + guest_faces(6)
OUT.write_text(json.dumps(faces, separators=(",", ":")))
print(f"wrote {len(faces)} faces to {OUT}")
