"""Build the fixed lobby layout and check its reserved walking/landing space.

Run with --check in CI; requires PyYAML. No runtime random placement.
"""
from pathlib import Path
import argparse
import math
import yaml

ROOT = Path(__file__).resolve().parents[1]
MAP = ROOT / 'assets/map/levels/gamenight_lobby.map.yaml'
DOORS = ROOT / 'src/gamenight/door_layout.rs'


def build():
    room = yaml.safe_load(MAP.read_text())
    tiles = room['layers'][0]['tiles']
    # Keep the room shell. Furniture must never become an accidental barrier.
    tiles[:] = [t for t in tiles if t['pos'][0] in (1, 38) or t['pos'][1] <= 2]
    # Separate station landings, not one continuous ceiling. All shelves use
    # the engine's existing one-way collision (rise through, land from above).
    for start, end, row in [(34, 36, 4), (33, 35, 6), (28, 30, 8), (24, 26, 10),
                            (27, 33, 12), (13, 24, 8), (10, 12, 9), (5, 9, 7),
                            (22, 24, 14), (16, 19, 15), (10, 12, 13), (6, 8, 11),
                            (2, 2, 4), (2, 3, 6)]:
        for x in range(start, end + 1):
            tiles.append(dict(pos=[x, row], idx=44 if x == start else 46 if x == end else 45,
                              collision='JumpThrough'))
    positions = {'qr_sign': [136., 352.], 'sign_in': [224., 263.],
                 'exit_door': [88., 134.], 'next_game': [620., 290.],
                 'music_screen': [976., 437.], 'music_pause': [940., 488.],
                 'music_skip': [1012., 488.]}
    for element in room['layers'][1]['elements']:
        key = Path(element['element']).name.split('.')[0]
        element['pos'] = positions[key]
    for element, x in zip(room['layers'][2]['elements'], [300., 500., 700., 1000.]):
        element['pos'] = [x, 122.]
    # The doorway footprint and its activation zone share these generated anchors.
    anchors = [160 + i * 112 for i in range(8)]
    rust = '// Generated by tools/layout_lobby.py; keep map and door anchors together.\n'
    rust += 'pub(super) const DOOR_X: [f32; 8] = [' + ', '.join(f'{x}.' for x in anchors) + '];\n'
    rust += 'pub(super) const DOOR_Y: f32 = 146.;\n'
    rust += 'pub(super) const PLAYER_Y: f32 = 120.;\n'
    validate(room, anchors)
    return yaml.safe_dump(room, sort_keys=False), rust


def validate(room, anchors):
    tiles = room['layers'][0]['tiles']
    for tile in tiles:
        x, y = tile['pos']
        shell = x in (1, 38) or y <= 2
        assert tile['collision'] == ('Solid' if shell else 'JumpThrough'), 'Incorrect platform collision'
    solids = [(t['pos'][0]*32, t['pos'][1]*32, 32, 32) for t in tiles
              if t['collision'] == 'Solid']
    def overlaps(a, b):
        x, y, w, h = a
        u, v, s, t = b
        return x < u+s and x+w > u and y < v+t and y+h > v
    # Keep the room-code wall plaque (including its shadow) clear of shelves.
    assert not any(overlaps((500, 582, 284, 110), (t['pos'][0]*32, t['pos'][1]*32, 32, 32))
                   for t in tiles), 'Platform overlaps room-code plaque'
    for x in anchors:
        assert not any(overlaps((x-48, 96, 96, 110), s) for s in solids), 'Blocked doorway'
    assert all(b-a >= 96 for a, b in zip(anchors, anchors[1:])), 'Overlapping doors'
    platforms = [(t['pos'][0]*32, (t['pos'][1]+1)*32, 32) for t in tiles
                 if t['collision'] == 'JumpThrough']
    # Both feet need a supported landing at the stairs and the three stations.
    for x, y in [(1120,160), (1088,224), (944,288), (816,352), (880,416),
                 (752,480), (592,512), (368,448), (240,384), (224,256), (80,160), (96,224),
                 (368,320), (500,288), (620,288), (740,288)]:
        assert all(any(left <= foot <= left+width and top == y for left, top, width in platforms)
                   for foot in (x-15, x+15)), 'Missing landing support'
    # Validate the intended staircase with the actual jump physics, leaving
    # 20px horizontal and 10px vertical safety margins for controller play.
    player = yaml.safe_load((ROOT / 'assets/player/skins/fishy/fishy.player.yaml').read_text())
    jump, speed, gravity = player['stats']['jump_speed'], player['stats']['air_speed'], player['gravity']
    # Stairs to music, upper loop, and branches to TV and sign-in.
    # Each pair starts from a safe take-off point on its supporting shelf.
    edges = [((1120,96),(1120,160)), ((1120,160),(1088,224)),
             ((1088,224),(960,288)), ((960,288),(832,352)),
             ((832,352),(880,416)), ((880,416),(784,480)),
             ((752,480),(624,512)), ((544,512),(400,448)),
             ((368,448),(272,384)), ((272,384),(368,320)),
             ((368,320),(288,256)), ((832,352),(736,288)),
             ((448,288),(368,320)), ((80,96),(80,160)),
             ((80,160),(96,224)), ((96,224),(224,256)),
             ((288,256),(368,320)), ((368,320),(272,384)),
             ((272,384),(368,448)), ((400,448),(544,512))]
    for (x, y), (u, v) in edges:
        rise = v-y
        assert rise+10 < jump*jump/(2*gravity), 'Platform too high'
        landing_time = (jump + math.sqrt(jump*jump-2*gravity*rise))/gravity
        assert abs(u-x)+20 < speed*landing_time, 'Platform too far'
        # Rise beside the solid ledge before moving across it. Sample the
        # whole 32x48 body at 240Hz, not just the distance between platforms.
        delay = 0.0 # Jump-through shelves allow immediate horizontal input.
        assert abs(u-x)/(landing_time-delay) < speed
        for step in range(1, math.ceil(landing_time*240)):
            t = step/240
            if t >= landing_time:
                break
            px = x + (u-x)*max(0, (t-delay)/(landing_time-delay))
            py = y + jump*t - gravity*t*t/2
            assert not any(overlaps((px-16,py,32,48),s) for s in solids), 'Jump path obstructed'
    # Gaps between the separate station shelves can be cleared with margin.
    for distance in (128, 160):
        assert distance+20 < speed*2*jump/gravity, 'Station gap too wide'
    # Upper controls have separate landings, with music buttons one
    # short jump above it. Check full player standing space at every control.
    for x, feet in [(224,270), (500,288), (620,288), (740,288), (940,495), (1012,495)]:
        assert not any(overlaps((x-16,feet,32,48),s) for s in solids), 'Blocked control'
    assert 495-416+10 < jump*jump/(2*gravity), 'Music controls too high'


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    room, rust = build()
    outputs = [(MAP, room), (DOORS, rust)]
    # Themes change decoration, never the validated collision/interaction layout.
    base = yaml.safe_load(room)
    for path in sorted((ROOT / 'assets/themes').glob('*/room.map.yaml')):
        themed = yaml.safe_load(path.read_text())
        themed['layers'] = base['layers']
        themed['grid_size'] = base['grid_size']
        themed['tile_size'] = base['tile_size']
        outputs.append((path, yaml.safe_dump(themed, sort_keys=False)))
    for path, content in outputs:
        if args.check:
            assert path.read_text() == content, f'Regenerate {path}'
        else:
            path.write_text(content)
    print('Lobby layout: eight clear doors, connected staircase and reachable control landings.')
