// Generated by scripts/build-docs.py.
pub fn page(slug: &str) -> Option<&'static str> {
    match slug {
        "" => Some(include_str!("docs.html")),
        "lifecycle" => Some(include_str!("docs-lifecycle.html")),
        "love" => Some(include_str!("docs-love.html")),
        "rust" => Some(include_str!("docs-rust.html")),
        "godot" => Some(include_str!("docs-godot.html")),
        "lobbies" => Some(include_str!("docs-lobbies.html")),
        "c" => Some(include_str!("docs-c.html")),
        "other-engines" => Some(include_str!("docs-other-engines.html")),
        "controllers" => Some(include_str!("docs-controllers.html")),
        "faces" => Some(include_str!("docs-faces.html")),
        "testing" => Some(include_str!("docs-testing.html")),
        "publishing" => Some(include_str!("docs-publishing.html")),
        "protocol" => Some(include_str!("docs-protocol.html")),
        _ => None,
    }
}
